//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SP_EF.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ALUMNOS
    {
        public int ID { get; set; }
        public string DOCUMENTO { get; set; }
        public string NOMBRE { get; set; }
        public string APELLIDO { get; set; }
        public string CORREO { get; set; }
        public System.DateTime FECHA_INGRESO { get; set; }
        public Nullable<int> EDAD { get; set; }
        public string TELEFONO { get; set; }
    }
}
