//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SP_EF.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CLASES
    {
        public int ID { get; set; }
        public Nullable<int> ID_PROFESOR { get; set; }
        public Nullable<int> ID_MATERIA { get; set; }
        public Nullable<int> ID_SALON { get; set; }
    }
}
